In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('news.csv', index_col=None)

In [3]:
dataset

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [4]:
dataset = dataset.drop("Unnamed: 0",axis=1)

In [5]:
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [6]:
y=dataset["label"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(dataset['text'], y,test_size=0.33, random_state=53)

In [10]:
hash_vectorizer = HashingVectorizer(
    stop_words='english',
    n_features=2**16,
    alternate_sign=False
)

hash_train = hash_vectorizer.transform(X_train)
print(hash_train)

hash_test = hash_vectorizer.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1115606 stored elements and shape (4244, 65536)>
  Coords	Values
  (1, 6711)	0.1336306209562122
  (1, 9728)	0.2672612419124244
  (1, 10746)	0.1336306209562122
  (1, 12144)	0.1336306209562122
  (1, 19960)	0.1336306209562122
  (1, 20099)	0.2672612419124244
  (1, 22739)	0.1336306209562122
  (1, 26073)	0.1336306209562122
  (1, 26381)	0.1336306209562122
  (1, 27086)	0.1336306209562122
  (1, 27898)	0.1336306209562122
  (1, 28535)	0.2672612419124244
  (1, 36157)	0.1336306209562122
  (1, 37027)	0.1336306209562122
  (1, 46353)	0.1336306209562122
  (1, 47677)	0.5345224838248488
  (1, 50038)	0.1336306209562122
  (1, 52456)	0.2672612419124244
  (1, 55852)	0.2672612419124244
  (1, 56432)	0.1336306209562122
  (1, 56466)	0.2672612419124244
  (1, 59068)	0.1336306209562122
  (1, 59564)	0.1336306209562122
  (2, 14361)	0.3333333333333333
  (2, 15347)	0.3333333333333333
  :	:
  (4243, 56207)	0.16957002568326646
  (4243, 56443)	0.028261670947211076
  (4243, 57521)	0.028261670947211076
  (4243, 57711)	0.028261670947211076
  (4243, 57757)	0.028261670947211076
  (4243, 57834)	0.05652334189442215
  (4243, 57923)	0.028261670947211076
  (4243, 58687)	0.028261670947211076
  (4243, 58885)	0.028261670947211076
  (4243, 59117)	0.028261670947211076
  (4243, 60375)	0.028261670947211076
  (4243, 60565)	0.05652334189442215
  (4243, 60576)	0.028261670947211076
  (4243, 61538)	0.05652334189442215
  (4243, 61566)	0.028261670947211076
  (4243, 61755)	0.05652334189442215
  (4243, 62366)	0.028261670947211076
  (4243, 62639)	0.028261670947211076
  (4243, 63685)	0.028261670947211076
  (4243, 63914)	0.05652334189442215
  (4243, 63968)	0.028261670947211076
  (4243, 64174)	0.028261670947211076
  (4243, 64273)	0.05652334189442215
  (4243, 64419)	0.028261670947211076
  (4243, 65453)	0.14130835473605538

In [11]:
dir(hash_vectorizer)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_class_level_metadata_request_values',
 '_get_doc_link',
 '_get_hasher',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sklearn_auto_wrap_output_keys',
 '_stop_words_id',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'alternate_sign',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'lowercase',
 'n_features',
 'ngram_range',
 'norm',
 'partial_fit',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform']

In [14]:
hash_vectorizer.n_features

65536

In [15]:
print(hash_train.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.04490133 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [16]:
# Create the model
clf = MultinomialNB()

# Train the model
clf.fit(hash_train, y_train)

# Predict the test data
pred = clf.predict(hash_test)

# Calculate accuracy
score = metrics.accuracy_score(y_test, pred)
print("Accuracy: %0.3f" % score)

# Confusion matrix
cm = metrics.confusion_matrix(
    y_test,
    pred,
    labels=['FAKE', 'REAL']
)

Accuracy: 0.869

In [17]:
from sklearn.metrics import classification_report

report=classification_report(y_test, pred)

In [18]:
print(report)

              precision    recall  f1-score   support

        FAKE       0.94      0.77      0.85      1008
        REAL       0.82      0.96      0.88      1083

    accuracy                           0.87      2091
   macro avg       0.88      0.87      0.87      2091
weighted avg       0.88      0.87      0.87      2091