In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('news.csv', index_col=None)

In [3]:
dataset

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [4]:
dataset=dataset.drop("Unnamed: 0",axis=1)

In [5]:
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [6]:
y=dataset["label"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(dataset['text'], y,test_size=0.33, random_state=53)

In [8]:
# Convert text into TF-IDF features
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

tfidf_train = tfidf_vectorizer.fit_transform(X_train)
print(tfidf_train)

tfidf_test = tfidf_vectorizer.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1119820 stored elements and shape (4244, 56922)>
  Coords	Values
  (1, 42470)	0.07711040274149526
  (1, 12105)	0.15008066461476866
  (1, 54177)	0.13782629144711137
  (1, 50628)	0.061296988343109586
  (1, 15924)	0.3479045460649079
  (1, 44520)	0.4973826512693341
  (1, 51896)	0.11596517664605868
  (1, 35783)	0.30902690818827977
  (1, 35256)	0.12628385718450857
  (1, 21881)	0.21271688045815978
  (1, 42534)	0.06081715886809217
  (1, 8399)	0.08729542880625335
  (1, 29531)	0.1454406205718245
  (1, 15927)	0.4973826512693341
  (1, 25686)	0.13550453594288983
  (1, 49203)	0.1672740861784377
  (1, 16814)	0.10404977746548139
  (1, 36087)	0.12648679854389897
  (1, 21568)	0.1007920919566398
  (1, 25684)	0.1030420922189754
  (1, 38823)	0.06048803110658644
  (1, 47506)	0.14539060877460044
  (1, 36831)	0.10772488937433067
  (2, 16972)	0.1606296088662543
  (2, 762)	0.48803966069171073
  :	:
  (4243, 41435)	0.02969665315895183
  (4243, 53607)	0.044665186536595916
  (4243, 659)	0.04293180970016178
  (4243, 38834)	0.037049324915825195
  (4243, 19003)	0.034437531050342904
  (4243, 11415)	0.04265300938931862
  (4243, 7545)	0.053202747014157864
  (4243, 22426)	0.04959478008035461
  (4243, 54007)	0.05100432396345157
  (4243, 7113)	0.055528486204784254
  (4243, 4932)	0.03711812880176506
  (4243, 39497)	0.04927770384099252
  (4243, 50053)	0.06673585515177109
  (4243, 38849)	0.048120818264389215
  (4243, 20702)	0.04867858477282518
  (4243, 42139)	0.04664685644842381
  (4243, 17247)	0.06113217067827768
  (4243, 50052)	0.05623192165966151
  (4243, 55228)	0.05623192165966151
  (4243, 29255)	0.05372450273788263
  (4243, 49435)	0.04265300938931862
  (4243, 11257)	0.06673585515177109
  (4243, 52945)	0.0644101159611447
  (4243, 20905)	0.05880643148765128
  (4243, 7962)	0.06673585515177109

In [10]:
dir(tfidf_train)

['T',
 '__abs__',
 '__abstractmethods__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pow__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__round__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__slots__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_abc_impl',
 '_add_dense',
 '_add_sparse',
 '_allow_nd',
 '_argminmax',
 '_argminmax_axis',
 '_ascontainer',
 '_asfptype',
 '_binopt',
 '_broadcast_to',
 '_bsr_container',
 '_comparison',
 '_container',
 '_coo_container',
 '_csc_container',
 '_csr_container',
 '_deduped_data',
 '_dia_container',
 '_divide',
 '_divide_sparse',
 '_dok_container',
 '_format',
 '_get_array',
 '_get_arrayXarray',
 '_get_arrayXint',
 '_get_arrayXslice',
 '_get_columnXarray',
 '_get_index_dtype',
 '_get_int',
 '_get_intXarray',
 '_get_intXint',
 '_get_intXslice',
 '_get_slice',
 '_get_sliceXarray',
 '_get_sliceXint',
 '_get_sliceXslice',
 '_get_submatrix',
 '_getcol',
 '_getmaxprint',
 '_getnnz',
 '_getrow',
 '_has_canonical_format',
 '_imag',
 '_insert_many',
 '_lil_container',
 '_major_index_fancy',
 '_major_slice',
 '_matmul_dispatch',
 '_matmul_multivector',
 '_matmul_sparse',
 '_matmul_vector',
 '_maximum_minimum',
 '_min_or_max',
 '_min_or_max_axis',
 '_minor_index_fancy',
 '_minor_reduce',
 '_minor_slice',
 '_mul_scalar',
 '_multiply_2d_with_broadcasting',
 '_prepare_indices',
 '_process_toarray_args',
 '_real',
 '_rmatmul_dispatch',
 '_rsub_dense',
 '_scalar_binopt',
 '_set_array',
 '_set_arrayXarray',
 '_set_arrayXarray_sparse',
 '_set_int',
 '_set_intXint',
 '_set_many',
 '_setdiag',
 '_shape',
 '_shape_as_2d',
 '_sub_dense',
 '_sub_sparse',
 '_swap',
 '_with_data',
 '_zero_many',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctanh',
 'argmax',
 'argmin',
 'asformat',
 'asfptype',
 'astype',
 'ceil',
 'check_format',
 'conj',
 'conjugate',
 'copy',
 'count_nonzero',
 'data',
 'deg2rad',
 'diagonal',
 'dot',
 'dtype',
 'eliminate_zeros',
 'expm1',
 'floor',
 'format',
 'getH',
 'get_shape',
 'getcol',
 'getformat',
 'getmaxprint',
 'getnnz',
 'getrow',
 'has_canonical_format',
 'has_sorted_indices',
 'imag',
 'indices',
 'indptr',
 'log1p',
 'max',
 'maximum',
 'maxprint',
 'mean',
 'min',
 'minimum',
 'multiply',
 'nanmax',
 'nanmin',
 'ndim',
 'nnz',
 'nonzero',
 'power',
 'prune',
 'rad2deg',
 'real',
 'reshape',
 'resize',
 'rint',
 'set_shape',
 'setdiag',
 'shape',
 'sign',
 'sin',
 'sinh',
 'size',
 'sort_indices',
 'sorted_indices',
 'sqrt',
 'sum',
 'sum_duplicates',
 'tan',
 'tanh',
 'toarray',
 'tobsr',
 'tocoo',
 'tocsc',
 'tocsr',
 'todense',
 'todia',
 'todok',
 'tolil',
 'trace',
 'transpose',
 'trunc']

In [11]:
len(tfidf_vectorizer.get_feature_names_out())

56922

In [12]:
print(tfidf_train.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [13]:
# Train the model
clf = MultinomialNB()
clf.fit(tfidf_train, y_train)

# Predict the test data
pred = clf.predict(tfidf_test)

# Calculate accuracy
score = metrics.accuracy_score(y_test, pred)
print("Accuracy: %0.3f" % score)

# Confusion matrix
cm = metrics.confusion_matrix(
    y_test,
    pred,
    labels=['FAKE', 'REAL']
)

Accuracy: 0.857